# Site settings
title: DayTrip Blog
email: info@godaytrip.com
description: > # this means to ignore newlines until "baseurl:"
  Daytrip’s blog—covering new spots, features, and product updates
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://godaytrip.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
